import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/Layout/Layout";
import styles from "../styles/Home.module.scss";
import data from "../data/effects";
import Card from "../components/Card/Card";

const Home: NextPage = () => {
  return (
    <Layout>
      <main className={styles.container}>
        <Head>
          <title>Animation Library</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {data.effects.map((card) => (
          <Card key={card.id} {...card} />
        ))}
      </main>
    </Layout>
  );
};

export default Home;
